language: cpp

# safelist
branches:
  only:
  - master
  - dev

compiler:
  - gcc

cache: ccache

os:
  - linux
services:redis-server

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libevent-dev
      - gcc-4.8
      - g++-4.8
      - libboost-all-dev

#before_install:

install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" && "$CXX" = "g++" ]]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
#before_script:
#./build.sh
script: 
./build.sh && ./bin/translib_tests
