language: cpp

# safelist
branches:
  only:
  - master
  - dev-branch

compiler:
  - gcc

cache: ccache

os:
  - linux


services:
  - redis-server

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libevent-dev
      - gcc-4.8
      - g++-4.8
      - libboost-all-dev

before_install:


install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi


script: chmod 755 build.sh&&./build.sh&&ls /usr/local/include&&mkdir build &&cd build&& cmake ..&&make


