language: cpp

# safelist
branches:
  only:
  - master
  - dev

compiler:
  - gcc

cache: ccache

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libevent-dev
      - gcc-4.8
      - g++-4.8
      - libboost-all-dev
      - git



before_install:
git clone https://github.com/Cylix/tacopie.git&&cd tacopie&&mkdir build&&cd build&& cmake ..&& make install

install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" && "$CXX" = "g++" ]]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: mkdir build && cd build && cmake .. && make && ./bin/translib_tests
