language: cpp

# safelist
branches:
  only:
  - master
  - dev

compiler:
  - gcc

cache: ccache

os:
  - linux


services:
  - redis-server

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libevent-dev
      - gcc-7.2
      - g++-7.2
      - libboost-all-dev

before_install:


install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi


script: mkdir -p build &&cd build&& cmake ..&&make&&bin/DBwrapper_example


